import json
import re
from src.social_media.media import get_youtube_transcript

# Tool definition schema for the LLM
YOUTUBE_TRANSCRIPT_TOOL = {
    "type": "function",
    "function": {
        "name": "get_youtube_transcript",
        "description": "Retrieves the full transcript/subtitles of a YouTube video given its video URL.",
        "parameters": {
            "type": "object",
            "properties": {
                "video_url": {
                    "type": "string",
                    "description": "The YouTube video URL (e.g., https://www.youtube.com/watch?v=QhIwyrd1jPg)"
                }
            },
            "required": ["video_url"]
        }
    }
}

def clean_json_response(content):
    """Cleans markdown JSON wrappers and extracts raw JSON blocks if generated by the LLM."""
    content = content.strip()
    # Attempt to extract outer JSON object if conversational wrapper text is present
    match = re.search(r"\{.*\}", content, re.DOTALL)
    if match:
        content = match.group(0)
    
    if content.startswith("```json"):
        content = content[7:]
    if content.startswith("```"):
        content = content[3:]
    if content.endswith("```"):
        content = content[:-3]
    return content.strip()

def analyze_video_with_llm(openai_client, model_name, video_url, video_title, categories_list):
    """
    Sends the YouTube URL to the LLM. 
    The LLM triggers the get_youtube_transcript tool, transcribes the video, 
    and returns sentiment, category/topic, and alert level.
    """
    print(f"   Analyzing video via LLM tool-calling: {video_url}...")
    categories_str = ", ".join(categories_list)
    
    messages = [
        {
            "role": "system",
            "content": (
                "You are an expert Competitive Intelligence Analyst. "
                "Your task is to analyze the provided YouTube video. "
                "You MUST call the 'get_youtube_transcript' tool to retrieve the text transcript "
                "of the video before performing your analysis. Do not make up or guess any details."
            )
        },
        {
            "role": "user",
            "content": (
                f"Analyze this YouTube video:\n"
                f"Title: {video_title}\n"
                f"URL: {video_url}\n\n"
                f"Please extract:\n"
                f"1. Sentiment of the video (Positive, Neutral, Negative)\n"
                f"2. Category/Topic of the video (Strictly choose one from: {categories_str})\n"
                f"3. Alert Level for competitive threat (Low, Medium, High)\n"
                f"4. A clean summary of the video transcript."
            )
        }
    ]
    
    try:
        response = openai_client.chat.completions.create(
            model=model_name,
            messages=messages,
            tools=[YOUTUBE_TRANSCRIPT_TOOL],
            tool_choice={"type": "function", "function": {"name": "get_youtube_transcript"}}
        )
        
        response_message = response.choices[0].message
        tool_calls = response_message.tool_calls
        
        if tool_calls:
            tool_call = tool_calls[0]
            function_args = json.loads(tool_call.function.arguments)
            target_url = function_args.get("video_url") or video_url
            
            transcript_text = get_youtube_transcript(target_url)
            
            messages.append(response_message)
            messages.append({
                "tool_call_id": tool_call.id,
                "role": "tool",
                "name": "get_youtube_transcript",
                "content": transcript_text
            })
            
            final_prompt = (
                f"Using the fetched transcript, output a structured JSON object containing:\n"
                f"{{\n"
                f'  "sentiment": "Positive/Neutral/Negative",\n'
                f'  "category": "Choose strictly one from: {categories_str}",\n'
                f'  "alert_level": "Low/Medium/High",\n'
                f'  "summary": "Brief summary of the video content"\n'
                f"}}\n"
                f"Return ONLY the raw JSON block without conversational text."
            )
            messages.append({"role": "user", "content": final_prompt})
            
            final_response = openai_client.chat.completions.create(
                model=model_name,
                messages=messages,
                temperature=0.1
            )
            
            content = clean_json_response(final_response.choices[0].message.content)
            result_data = json.loads(content)
            result_data["transcript"] = transcript_text
            return result_data
            
    except Exception as e:
        print(f"      ⚠️ LLM Tool-calling analysis failed: {str(e)}")
        try:
            print(f"      Raw Response Content: {final_response.choices[0].message.content}")
        except Exception:
            pass
        
    return {
        "sentiment": "Neutral",
        "category": "General Industry News",
        "alert_level": "Low",
        "summary": "Failed to analyze video transcript via LLM.",
        "transcript": "[Failed to fetch]"
    }

def analyze_post_with_llm(openai_client, model_name, platform, competitor, post_text, image_text, video_transcript, categories_list):
    """
    Sends a generic post (from X, Instagram, LinkedIn) to the LLM
    to classify category, sentiment, alert level, and generate an AI summary.
    """
    print(f"   Analyzing post via LLM: [{platform}] from {competitor}...")
    categories_str = ", ".join(categories_list)
    
    prompt = f"""
    You are a Competitive Intelligence Analyst. Analyze the following competitor social media post:
    
    Platform: {platform}
    Competitor: {competitor}
    Post Caption/Text: {post_text}
    Extracted Image Text (if any): {image_text}
    Video Transcript (if any): {video_transcript}
    
    Provide the output strictly in this JSON format:
    {{
        "sentiment": "Positive / Neutral / Negative",
        "category": "Strictly choose one from: {categories_str}",
        "alert_level": "Low / Medium / High",
        "summary": "Brief 1-2 sentence summary of competitor activity"
    }}
    Return ONLY the raw JSON block without conversational text.
    """
    
    try:
        response = openai_client.chat.completions.create(
            model=model_name,
            messages=[
                {"role": "system", "content": "You are a competitive intelligence system. Output strictly formatted JSON only."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.1
        )
        content = clean_json_response(response.choices[0].message.content)
        result_data = json.loads(content)
        return result_data
    except Exception as e:
        print(f"      ⚠️ LLM Post analysis failed: {str(e)}")
        try:
            print(f"      Raw Response Content: {response.choices[0].message.content}")
        except Exception:
            pass
        
    return {
        "sentiment": "Neutral",
        "category": "General Industry News",
        "alert_level": "Low",
        "summary": "Failed to analyze post via LLM."
    }
